sudo: false
dist: bionic
language: node_js
cache: npm
notifications:
  email: false
node_js:
  - '8'
  - '10'
  - '12'
install:
  - npm ci
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
